# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/shohei/graphic_display/graphic_display.cache/wt [current_project]
set_property parent.project_path C:/Users/shohei/graphic_display/graphic_display.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/shohei/graphic_display/graphic_display.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog C:/Users/shohei/graphic_display/graphic_display.srcs/sources_1/new/vga_param.vh
read_verilog -library xil_defaultlib {
  C:/Users/shohei/graphic_display/graphic_display.srcs/sources_1/new/pckgen.v
  C:/Users/shohei/graphic_display/graphic_display.srcs/sources_1/new/syncgen.v
  C:/Users/shohei/graphic_display/graphic_display.srcs/sources_1/new/pattern.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/shohei/Downloads/ZYBO_Master.xdc
set_property used_in_implementation false [get_files C:/Users/shohei/Downloads/ZYBO_Master.xdc]


synth_design -top pattern -part xc7z010clg400-1


write_checkpoint -force -noxdef pattern.dcp

catch { report_utilization -file pattern_utilization_synth.rpt -pb pattern_utilization_synth.pb }
